/*
 * ChangeAttribute.java
 *
 * Generated by Protege plugin Beanynizer. 
 * Changes will be lost! 
 */
package jadex.tools.ontology;



/**
 *  Java class for concept ChangeAttribute of jadex.tools.introspector ontology.
 */
public class ChangeAttribute	extends ElementAction implements java.beans.BeanInfo 
{
	//-------- constants ----------

	//-------- attributes ----------

	/** The name of the attribute. */
	protected  String  attributename;

	/** Attribute for slot value2. */
	protected  String  value;

	//-------- constructors --------

	/**
	 *  Default Constructor. <br>
	 *  Create a new <code>ChangeAttribute</code>.
	 */
	public ChangeAttribute()  {
	}

	/**
	 *  Init Constructor. <br>
	 *  Create a new ChangeAttribute.<br>
	 *  Initializes the object with required attributes.
	 * @param attributename
	 * @param elementname
	 * @param elementtype
	 * @param tooltype
	 * @param value
	 */
	public ChangeAttribute(String attributename, String elementname, String elementtype, String tooltype, String value)  {
		this();
		setAttributeName(attributename);
		setElementName(elementname);
		setElementType(elementtype);
		setToolType(tooltype);
		setValue(value);
	}

	//-------- accessor methods --------

	/**
	 *  Get the attribute-name of this ChangeAttribute.
	 *  The name of the attribute.
	 * @return attribute-name
	 */
	public String  getAttributeName() {
		return this.attributename;
	}

	/**
	 *  Set the attribute-name of this ChangeAttribute.
	 *  The name of the attribute.
	 * @param attributename the value to be set
	 */
	public void  setAttributeName(String attributename) {
		this.attributename = attributename;
	}

	/**
	 *  Get the value2 of this ChangeAttribute.
	 * @return value2
	 */
	public String  getValue() {
		return this.value;
	}

	/**
	 *  Set the value2 of this ChangeAttribute.
	 * @param value the value to be set
	 */
	public void  setValue(String value) {
		this.value = value;
	}

	//-------- bean related methods --------

	/** The property descriptors, constructed on first access. */
	private java.beans.PropertyDescriptor[] pds = null;

	/**
	 *  Get the bean descriptor.
	 *  @return The bean descriptor.
	 */
	public java.beans.BeanDescriptor getBeanDescriptor() {
		return null;
	}

	/**
	 *  Get the property descriptors.
	 *  @return The property descriptors.
	 */
	public java.beans.PropertyDescriptor[] getPropertyDescriptors() {
		if(pds==null) {
			try {
				pds = new java.beans.PropertyDescriptor[]{
					 new java.beans.PropertyDescriptor("attributeName", this.getClass(), "getAttributeName", "setAttributeName")
					, new java.beans.PropertyDescriptor("value", this.getClass(), "getValue", "setValue")
				};
				java.beans.PropertyDescriptor[] spds = super.getPropertyDescriptors();
				int	l1	= pds.length;
				int	l2	= spds.length;
				Object	res	= java.lang.reflect.Array.newInstance(java.beans.PropertyDescriptor.class, l1+l2);
				System.arraycopy(pds, 0, res, 0, l1);
				System.arraycopy(spds, 0, res, l1, l2);
				pds = (java.beans.PropertyDescriptor[])res;
			}
			catch(Exception e) {
				e.printStackTrace();
			}
		}
		return pds;
	}

	/**
	 *  Get the default property index.
	 *  @return The property index.
	 */
	public int getDefaultPropertyIndex() {
		return -1;
	}

	/**
	 *  Get the event set descriptors.
	 *  @return The event set descriptors.
	 */
	public java.beans.EventSetDescriptor[] getEventSetDescriptors() {
		return null;
	}

	/**
	 *  Get the default event index.
	 *  @return The default event index.
	 */
	public int getDefaultEventIndex() {
		return -1;
	}

	/**
	 *  Get the method descriptors.
	 *  @return The method descriptors.
	 */
	public java.beans.MethodDescriptor[] getMethodDescriptors() {
		return null;
	}

	/**
	 *  Get additional bean info.
	 *  @return Get additional bean info.
	 */
	public java.beans.BeanInfo[] getAdditionalBeanInfo() {
		return null;
	}

	/**
	 *  Get the icon.
	 *  @return The icon.
	 */
	public java.awt.Image getIcon(int iconKind) {
		return null;
	}

	/**
	 *  Load the image.
	 *  @return The image.
	 */
	public java.awt.Image loadImage(final String resourceName) {
		try {
			final Class c = getClass();
			java.awt.image.ImageProducer ip = (java.awt.image.ImageProducer)
				java.security.AccessController.doPrivileged(new java.security.PrivilegedAction() {
					public Object run(){
						java.net.URL url;
						if((url = c.getResource(resourceName))==null) {
							return null;
						}
						else {
							try {
								return url.getContent();
							}
							catch(java.io.IOException ioe) {
								return null;
							}
						}
					}
				});
			if(ip==null)
				return null;
			java.awt.Toolkit tk = java.awt.Toolkit.getDefaultToolkit();
			return tk.createImage(ip);
		}
		catch(Exception ex) {
			return null;
		}
	}

	//-------- additional methods --------

	/**
	 *  Get a string representation of this ChangeAttribute.
	 *  @return The string representation.
	 */
	public String toString() {
		return "ChangeAttribute("
		+ "attributename="+getAttributeName()
		+ ", elementname="+getElementName()
		+ ", elementtype="+getElementType()
		+ ", tooltype="+getToolType()
		+ ", value="+getValue()
           + ")";
	}

}
