/*
 * ElementAction.java
 *
 * Generated by Protege plugin Beanynizer. 
 * Changes will be lost! 
 */
package jadex.tools.ontology;



/**
 *  Java class for concept ElementAction of jadex.tools.introspector ontology.
 */
public class ElementAction	extends ToolAction implements java.beans.BeanInfo 
{
	//-------- constants ----------

	//-------- attributes ----------

	/** The scope of the element. */
	protected  String  scope;

	/** The name of the element. */
	protected  String  elementname;

	/** The type of the element
(e.g. "goal"). */
	protected  String  elementtype;

	//-------- constructors --------

	/**
	 *  Default Constructor. <br>
	 *  Create a new <code>ElementAction</code>.
	 */
	public ElementAction()  {
	}

	/**
	 *  Init Constructor. <br>
	 *  Create a new ElementAction.<br>
	 *  Initializes the object with required attributes.
	 * @param elementname
	 * @param elementtype
	 * @param tooltype
	 */
	public ElementAction(String elementname, String elementtype, String tooltype)  {
		this();
		setElementName(elementname);
		setElementType(elementtype);
		setToolType(tooltype);
	}

	//-------- accessor methods --------

	/**
	 *  Get the scope of this ElementAction.
	 *  The scope of the element.
	 * @return scope
	 */
	public String  getScope() {
		return this.scope;
	}

	/**
	 *  Set the scope of this ElementAction.
	 *  The scope of the element.
	 * @param scope the value to be set
	 */
	public void  setScope(String scope) {
		this.scope = scope;
	}

	/**
	 *  Get the element-name of this ElementAction.
	 *  The name of the element.
	 * @return element-name
	 */
	public String  getElementName() {
		return this.elementname;
	}

	/**
	 *  Set the element-name of this ElementAction.
	 *  The name of the element.
	 * @param elementname the value to be set
	 */
	public void  setElementName(String elementname) {
		this.elementname = elementname;
	}

	/**
	 *  Get the element-type of this ElementAction.
	 *  The type of the element
(e.g. "goal").
	 * @return element-type
	 */
	public String  getElementType() {
		return this.elementtype;
	}

	/**
	 *  Set the element-type of this ElementAction.
	 *  The type of the element
(e.g. "goal").
	 * @param elementtype the value to be set
	 */
	public void  setElementType(String elementtype) {
		this.elementtype = elementtype;
	}

	//-------- bean related methods --------

	/** The property descriptors, constructed on first access. */
	private java.beans.PropertyDescriptor[] pds = null;

	/**
	 *  Get the bean descriptor.
	 *  @return The bean descriptor.
	 */
	public java.beans.BeanDescriptor getBeanDescriptor() {
		return null;
	}

	/**
	 *  Get the property descriptors.
	 *  @return The property descriptors.
	 */
	public java.beans.PropertyDescriptor[] getPropertyDescriptors() {
		if(pds==null) {
			try {
				pds = new java.beans.PropertyDescriptor[]{
					 new java.beans.PropertyDescriptor("scope", this.getClass(), "getScope", "setScope")
					, new java.beans.PropertyDescriptor("elementName", this.getClass(), "getElementName", "setElementName")
					, new java.beans.PropertyDescriptor("elementType", this.getClass(), "getElementType", "setElementType")
				};
				java.beans.PropertyDescriptor[] spds = super.getPropertyDescriptors();
				int	l1	= pds.length;
				int	l2	= spds.length;
				Object	res	= java.lang.reflect.Array.newInstance(java.beans.PropertyDescriptor.class, l1+l2);
				System.arraycopy(pds, 0, res, 0, l1);
				System.arraycopy(spds, 0, res, l1, l2);
				pds = (java.beans.PropertyDescriptor[])res;
			}
			catch(Exception e) {
				e.printStackTrace();
			}
		}
		return pds;
	}

	/**
	 *  Get the default property index.
	 *  @return The property index.
	 */
	public int getDefaultPropertyIndex() {
		return -1;
	}

	/**
	 *  Get the event set descriptors.
	 *  @return The event set descriptors.
	 */
	public java.beans.EventSetDescriptor[] getEventSetDescriptors() {
		return null;
	}

	/**
	 *  Get the default event index.
	 *  @return The default event index.
	 */
	public int getDefaultEventIndex() {
		return -1;
	}

	/**
	 *  Get the method descriptors.
	 *  @return The method descriptors.
	 */
	public java.beans.MethodDescriptor[] getMethodDescriptors() {
		return null;
	}

	/**
	 *  Get additional bean info.
	 *  @return Get additional bean info.
	 */
	public java.beans.BeanInfo[] getAdditionalBeanInfo() {
		return null;
	}

	/**
	 *  Get the icon.
	 *  @return The icon.
	 */
	public java.awt.Image getIcon(int iconKind) {
		return null;
	}

	/**
	 *  Load the image.
	 *  @return The image.
	 */
	public java.awt.Image loadImage(final String resourceName) {
		try {
			final Class c = getClass();
			java.awt.image.ImageProducer ip = (java.awt.image.ImageProducer)
				java.security.AccessController.doPrivileged(new java.security.PrivilegedAction() {
					public Object run(){
						java.net.URL url;
						if((url = c.getResource(resourceName))==null) {
							return null;
						}
						else {
							try {
								return url.getContent();
							}
							catch(java.io.IOException ioe) {
								return null;
							}
						}
					}
				});
			if(ip==null)
				return null;
			java.awt.Toolkit tk = java.awt.Toolkit.getDefaultToolkit();
			return tk.createImage(ip);
		}
		catch(Exception ex) {
			return null;
		}
	}

	//-------- additional methods --------

	/**
	 *  Get a string representation of this ElementAction.
	 *  @return The string representation.
	 */
	public String toString() {
		return "ElementAction("
		+ "elementname="+getElementName()
		+ ", elementtype="+getElementType()
		+ ", tooltype="+getToolType()
           + ")";
	}

}
