/*
 * OGoal.java
 *
 * Generated by Protege plugin Beanynizer. 
 * Changes will be lost! 
 */
package jadex.tools.ontology;



/**
 *  Java class for concept OGoal of jadex.tools.tracer ontology.
 */
public class OGoal	extends OTrace implements java.beans.BeanInfo 
{
	//-------- constants ----------

	/** Predefined value "ADOPTED" for slot goal_state. */
	public static String  GOALSTATE_ADOPTED  = "ADOPTED";
	/** Predefined value "REMOVED" for slot goal_state. */
	public static String  GOALSTATE_REMOVED  = "REMOVED";

	/** Predefined value "achieve" for slot goal-kind. */
	public static String  GOALKIND_ACHIEVE  = "achieve";
	/** Predefined value "maintain" for slot goal-kind. */
	public static String  GOALKIND_MAINTAIN  = "maintain";
	/** Predefined value "perform" for slot goal-kind. */
	public static String  GOALKIND_PERFORM  = "perform";
	/** Predefined value "query" for slot goal-kind. */
	public static String  GOALKIND_QUERY  = "query";
	/** Predefined value "meta" for slot goal-kind. */
	public static String  GOALKIND_META  = "meta";

	//-------- attributes ----------

	/** Attribute for slot goal_state. */
	protected  String  goalstate;

	/** Attribute for slot goal-kind. */
	protected  String  goalkind;

	//-------- constructors --------

	/**
	 *  Default Constructor. <br>
	 *  Create a new <code>OGoal</code>.
	 */
	public OGoal()  {
	}

	/**
	 *  Init Constructor. <br>
	 *  Create a new OGoal.<br>
	 *  Initializes the object with required attributes.
	 * @param goalstate
	 * @param name
	 * @param seq
	 * @param thread
	 * @param time
	 * @param value
	 */
	public OGoal(String goalstate, String name, String seq, String thread, String time, String value)  {
		this();
		setGoalState(goalstate);
		setName(name);
		setSeq(seq);
		setThread(thread);
		setTime(time);
		setValue(value);
	}

	//-------- accessor methods --------

	/**
	 *  Get the goal_state of this OGoal.
	 * @return goal_state
	 */
	public String  getGoalState() {
		return this.goalstate;
	}

	/**
	 *  Set the goal_state of this OGoal.
	 * @param goalstate the value to be set
	 */
	public void  setGoalState(String goalstate) {
		this.goalstate = goalstate;
	}

	/**
	 *  Get the goal-kind of this OGoal.
	 * @return goal-kind
	 */
	public String  getGoalKind() {
		return this.goalkind;
	}

	/**
	 *  Set the goal-kind of this OGoal.
	 * @param goalkind the value to be set
	 */
	public void  setGoalKind(String goalkind) {
		this.goalkind = goalkind;
	}

	//-------- bean related methods --------

	/** The property descriptors, constructed on first access. */
	private java.beans.PropertyDescriptor[] pds = null;

	/**
	 *  Get the bean descriptor.
	 *  @return The bean descriptor.
	 */
	public java.beans.BeanDescriptor getBeanDescriptor() {
		return null;
	}

	/**
	 *  Get the property descriptors.
	 *  @return The property descriptors.
	 */
	public java.beans.PropertyDescriptor[] getPropertyDescriptors() {
		if(pds==null) {
			try {
				pds = new java.beans.PropertyDescriptor[]{
					 new java.beans.PropertyDescriptor("goalState", this.getClass(), "getGoalState", "setGoalState")
					, new java.beans.PropertyDescriptor("goalKind", this.getClass(), "getGoalKind", "setGoalKind")
				};
				java.beans.PropertyDescriptor[] spds = super.getPropertyDescriptors();
				int	l1	= pds.length;
				int	l2	= spds.length;
				Object	res	= java.lang.reflect.Array.newInstance(java.beans.PropertyDescriptor.class, l1+l2);
				System.arraycopy(pds, 0, res, 0, l1);
				System.arraycopy(spds, 0, res, l1, l2);
				pds = (java.beans.PropertyDescriptor[])res;
			}
			catch(Exception e) {
				e.printStackTrace();
			}
		}
		return pds;
	}

	/**
	 *  Get the default property index.
	 *  @return The property index.
	 */
	public int getDefaultPropertyIndex() {
		return -1;
	}

	/**
	 *  Get the event set descriptors.
	 *  @return The event set descriptors.
	 */
	public java.beans.EventSetDescriptor[] getEventSetDescriptors() {
		return null;
	}

	/**
	 *  Get the default event index.
	 *  @return The default event index.
	 */
	public int getDefaultEventIndex() {
		return -1;
	}

	/**
	 *  Get the method descriptors.
	 *  @return The method descriptors.
	 */
	public java.beans.MethodDescriptor[] getMethodDescriptors() {
		return null;
	}

	/**
	 *  Get additional bean info.
	 *  @return Get additional bean info.
	 */
	public java.beans.BeanInfo[] getAdditionalBeanInfo() {
		return null;
	}

	/**
	 *  Get the icon.
	 *  @return The icon.
	 */
	public java.awt.Image getIcon(int iconKind) {
		return null;
	}

	/**
	 *  Load the image.
	 *  @return The image.
	 */
	public java.awt.Image loadImage(final String resourceName) {
		try {
			final Class c = getClass();
			java.awt.image.ImageProducer ip = (java.awt.image.ImageProducer)
				java.security.AccessController.doPrivileged(new java.security.PrivilegedAction() {
					public Object run(){
						java.net.URL url;
						if((url = c.getResource(resourceName))==null) {
							return null;
						}
						else {
							try {
								return url.getContent();
							}
							catch(java.io.IOException ioe) {
								return null;
							}
						}
					}
				});
			if(ip==null)
				return null;
			java.awt.Toolkit tk = java.awt.Toolkit.getDefaultToolkit();
			return tk.createImage(ip);
		}
		catch(Exception ex) {
			return null;
		}
	}

	//-------- additional methods --------

	/**
	 *  Get a string representation of this OGoal.
	 *  @return The string representation.
	 */
	public String toString() {
		return "OGoal("
		+ "goalstate="+getGoalState()
		+ ", name="+getName()
		+ ", seq="+getSeq()
		+ ", thread="+getThread()
		+ ", time="+getTime()
		+ ", value="+getValue()
           + ")";
	}

}
