/*
 * OPlan.java
 *
 * Generated by Protege plugin Beanynizer. 
 * Changes will be lost! 
 */
package jadex.tools.ontology;



/**
 *  Java class for concept OPlan of jadex.tools.tracer ontology.
 */
public class OPlan	extends OTrace implements java.beans.BeanInfo 
{
	//-------- constants ----------

	/** Predefined value "STARTED" for slot plan_state. */
	public static String  PLANSTATE_STARTED  = "STARTED";
	/** Predefined value "TERMINATED" for slot plan_state. */
	public static String  PLANSTATE_TERMINATED  = "TERMINATED";

	//-------- attributes ----------

	/** Attribute for slot plan_state. */
	protected  String  planstate;

	//-------- constructors --------

	/**
	 *  Default Constructor. <br>
	 *  Create a new <code>OPlan</code>.
	 */
	public OPlan()  {
	}

	/**
	 *  Init Constructor. <br>
	 *  Create a new OPlan.<br>
	 *  Initializes the object with required attributes.
	 * @param name
	 * @param planstate
	 * @param seq
	 * @param thread
	 * @param time
	 * @param value
	 */
	public OPlan(String name, String planstate, String seq, String thread, String time, String value)  {
		this();
		setName(name);
		setPlanState(planstate);
		setSeq(seq);
		setThread(thread);
		setTime(time);
		setValue(value);
	}

	//-------- accessor methods --------

	/**
	 *  Get the plan_state of this OPlan.
	 * @return plan_state
	 */
	public String  getPlanState() {
		return this.planstate;
	}

	/**
	 *  Set the plan_state of this OPlan.
	 * @param planstate the value to be set
	 */
	public void  setPlanState(String planstate) {
		this.planstate = planstate;
	}

	//-------- bean related methods --------

	/** The property descriptors, constructed on first access. */
	private java.beans.PropertyDescriptor[] pds = null;

	/**
	 *  Get the bean descriptor.
	 *  @return The bean descriptor.
	 */
	public java.beans.BeanDescriptor getBeanDescriptor() {
		return null;
	}

	/**
	 *  Get the property descriptors.
	 *  @return The property descriptors.
	 */
	public java.beans.PropertyDescriptor[] getPropertyDescriptors() {
		if(pds==null) {
			try {
				pds = new java.beans.PropertyDescriptor[]{
					 new java.beans.PropertyDescriptor("planState", this.getClass(), "getPlanState", "setPlanState")
				};
				java.beans.PropertyDescriptor[] spds = super.getPropertyDescriptors();
				int	l1	= pds.length;
				int	l2	= spds.length;
				Object	res	= java.lang.reflect.Array.newInstance(java.beans.PropertyDescriptor.class, l1+l2);
				System.arraycopy(pds, 0, res, 0, l1);
				System.arraycopy(spds, 0, res, l1, l2);
				pds = (java.beans.PropertyDescriptor[])res;
			}
			catch(Exception e) {
				e.printStackTrace();
			}
		}
		return pds;
	}

	/**
	 *  Get the default property index.
	 *  @return The property index.
	 */
	public int getDefaultPropertyIndex() {
		return -1;
	}

	/**
	 *  Get the event set descriptors.
	 *  @return The event set descriptors.
	 */
	public java.beans.EventSetDescriptor[] getEventSetDescriptors() {
		return null;
	}

	/**
	 *  Get the default event index.
	 *  @return The default event index.
	 */
	public int getDefaultEventIndex() {
		return -1;
	}

	/**
	 *  Get the method descriptors.
	 *  @return The method descriptors.
	 */
	public java.beans.MethodDescriptor[] getMethodDescriptors() {
		return null;
	}

	/**
	 *  Get additional bean info.
	 *  @return Get additional bean info.
	 */
	public java.beans.BeanInfo[] getAdditionalBeanInfo() {
		return null;
	}

	/**
	 *  Get the icon.
	 *  @return The icon.
	 */
	public java.awt.Image getIcon(int iconKind) {
		return null;
	}

	/**
	 *  Load the image.
	 *  @return The image.
	 */
	public java.awt.Image loadImage(final String resourceName) {
		try {
			final Class c = getClass();
			java.awt.image.ImageProducer ip = (java.awt.image.ImageProducer)
				java.security.AccessController.doPrivileged(new java.security.PrivilegedAction() {
					public Object run(){
						java.net.URL url;
						if((url = c.getResource(resourceName))==null) {
							return null;
						}
						else {
							try {
								return url.getContent();
							}
							catch(java.io.IOException ioe) {
								return null;
							}
						}
					}
				});
			if(ip==null)
				return null;
			java.awt.Toolkit tk = java.awt.Toolkit.getDefaultToolkit();
			return tk.createImage(ip);
		}
		catch(Exception ex) {
			return null;
		}
	}

	//-------- additional methods --------

	/**
	 *  Get a string representation of this OPlan.
	 *  @return The string representation.
	 */
	public String toString() {
		return "OPlan("
		+ "name="+getName()
		+ ", planstate="+getPlanState()
		+ ", seq="+getSeq()
		+ ", thread="+getThread()
		+ ", time="+getTime()
		+ ", value="+getValue()
           + ")";
	}

}
