/*
 * PerformAction.java
 *
 * Generated by Protege plugin Beanynizer. 
 * Changes will be lost! 
 */
package jadex.tools.ontology;

import java.util.ArrayList;
import java.util.List;


/**
 *  Java class for concept PerformAction of jadex.tools.introspector ontology.
 */
public class PerformAction	extends ElementAction implements java.beans.BeanInfo 
{
	//-------- constants ----------

	//-------- attributes ----------

	/** The name of the operation to invoke. */
	protected  String  actionname;

	/** Attribute for slot action-arguments. */
	protected  List  arguments;

	//-------- constructors --------

	/**
	 *  Default Constructor. <br>
	 *  Create a new <code>PerformAction</code>.
	 */
	public PerformAction()  {
		this.arguments  = new ArrayList();
	}

	/**
	 *  Init Constructor. <br>
	 *  Create a new PerformAction.<br>
	 *  Initializes the object with required attributes.
	 * @param actionname
	 * @param elementname
	 * @param elementtype
	 * @param tooltype
	 */
	public PerformAction(String actionname, String elementname, String elementtype, String tooltype)  {
		this();
		setActionName(actionname);
		setElementName(elementname);
		setElementType(elementtype);
		setToolType(tooltype);
	}

	//-------- accessor methods --------

	/**
	 *  Get the action-name of this PerformAction.
	 *  The name of the operation to invoke.
	 * @return action-name
	 */
	public String  getActionName() {
		return this.actionname;
	}

	/**
	 *  Set the action-name of this PerformAction.
	 *  The name of the operation to invoke.
	 * @param actionname the value to be set
	 */
	public void  setActionName(String actionname) {
		this.actionname = actionname;
	}

	/**
	 *  Get the action-arguments of this PerformAction.
	 * @return action-arguments
	 */
	public String[]  getArguments() {
		return (String[])arguments.toArray(new String [arguments.size()]);
	}

	/**
	 *  Set the action-arguments of this PerformAction.
	 * @param arguments the value to be set
	 */
	public void  setArguments(String[] arguments) {
		this.arguments.clear();
		for(int i=0; i<arguments.length; i++)
			this.arguments.add(arguments[i]);
	}

	/**
	 *  Get an action-arguments of this PerformAction.
	 *  @param idx The index.
	 *  @return action-arguments
	 */
	public String  getArgument(int idx) {
		return (String)this.arguments.get(idx);
	}

	/**
	 *  Set a action-argument to this PerformAction.
	 *  @param idx The index.
	 *  @param argument a value to be added
	 */
	public void  setArgument(int idx, String argument) {
		this.arguments.set(idx, argument);
	}

	/**
	 *  Add a action-argument to this PerformAction.
	 *  @param argument a value to be removed
	 */
	public void  addArgument(String argument)  {
		this.arguments.add(argument);
	}

	/**
	 *  Remove a action-argument from this PerformAction.
	 *  @param argument a value to be removed
	 *  @return  True when the action-arguments have changed.
	 */
	public boolean  removeArgument(String argument)  {
		return this.arguments.remove(argument);
	}


	//-------- bean related methods --------

	/** The property descriptors, constructed on first access. */
	private java.beans.PropertyDescriptor[] pds = null;

	/**
	 *  Get the bean descriptor.
	 *  @return The bean descriptor.
	 */
	public java.beans.BeanDescriptor getBeanDescriptor() {
		return null;
	}

	/**
	 *  Get the property descriptors.
	 *  @return The property descriptors.
	 */
	public java.beans.PropertyDescriptor[] getPropertyDescriptors() {
		if(pds==null) {
			try {
				pds = new java.beans.PropertyDescriptor[]{
					 new java.beans.PropertyDescriptor("actionName", this.getClass(), "getActionName", "setActionName")
					, new java.beans.IndexedPropertyDescriptor("arguments", this.getClass(),
						"getArguments", "setArguments", "getArgument", "setArgument")
				};
				java.beans.PropertyDescriptor[] spds = super.getPropertyDescriptors();
				int	l1	= pds.length;
				int	l2	= spds.length;
				Object	res	= java.lang.reflect.Array.newInstance(java.beans.PropertyDescriptor.class, l1+l2);
				System.arraycopy(pds, 0, res, 0, l1);
				System.arraycopy(spds, 0, res, l1, l2);
				pds = (java.beans.PropertyDescriptor[])res;
			}
			catch(Exception e) {
				e.printStackTrace();
			}
		}
		return pds;
	}

	/**
	 *  Get the default property index.
	 *  @return The property index.
	 */
	public int getDefaultPropertyIndex() {
		return -1;
	}

	/**
	 *  Get the event set descriptors.
	 *  @return The event set descriptors.
	 */
	public java.beans.EventSetDescriptor[] getEventSetDescriptors() {
		return null;
	}

	/**
	 *  Get the default event index.
	 *  @return The default event index.
	 */
	public int getDefaultEventIndex() {
		return -1;
	}

	/**
	 *  Get the method descriptors.
	 *  @return The method descriptors.
	 */
	public java.beans.MethodDescriptor[] getMethodDescriptors() {
		return null;
	}

	/**
	 *  Get additional bean info.
	 *  @return Get additional bean info.
	 */
	public java.beans.BeanInfo[] getAdditionalBeanInfo() {
		return null;
	}

	/**
	 *  Get the icon.
	 *  @return The icon.
	 */
	public java.awt.Image getIcon(int iconKind) {
		return null;
	}

	/**
	 *  Load the image.
	 *  @return The image.
	 */
	public java.awt.Image loadImage(final String resourceName) {
		try {
			final Class c = getClass();
			java.awt.image.ImageProducer ip = (java.awt.image.ImageProducer)
				java.security.AccessController.doPrivileged(new java.security.PrivilegedAction() {
					public Object run(){
						java.net.URL url;
						if((url = c.getResource(resourceName))==null) {
							return null;
						}
						else {
							try {
								return url.getContent();
							}
							catch(java.io.IOException ioe) {
								return null;
							}
						}
					}
				});
			if(ip==null)
				return null;
			java.awt.Toolkit tk = java.awt.Toolkit.getDefaultToolkit();
			return tk.createImage(ip);
		}
		catch(Exception ex) {
			return null;
		}
	}

	//-------- additional methods --------

	/**
	 *  Get a string representation of this PerformAction.
	 *  @return The string representation.
	 */
	public String toString() {
		return "PerformAction("
		+ "actionname="+getActionName()
		+ ", elementname="+getElementName()
		+ ", elementtype="+getElementType()
		+ ", tooltype="+getToolType()
           + ")";
	}

}
