/*
 * Register.java
 *
 * Generated by Protege plugin Beanynizer. 
 * Changes will be lost! 
 */
package jadex.tools.ontology;

import java.util.ArrayList;
import java.util.List;


/**
 *  Java class for concept Register of jadex.tools.introspector ontology.
 */
public class Register	extends ToolRequest implements java.beans.BeanInfo 
{
	//-------- constants ----------

	//-------- attributes ----------

	/** The system event types to be propagated to the tool. */
	protected  List  eventtypes;

	//-------- constructors --------

	/**
	 *  Default Constructor. <br>
	 *  Create a new <code>Register</code>.
	 */
	public Register()  {
		this.eventtypes  = new ArrayList();
	}

	/**
	 *  Init Constructor. <br>
	 *  Create a new Register.<br>
	 *  Initializes the object with required attributes.
	 * @param tooltype
	 */
	public Register(String tooltype)  {
		this();
		setToolType(tooltype);
	}

	//-------- accessor methods --------

	/**
	 *  Get the event-types of this Register.
	 *   The system event types to be propagated to the tool.
	 * @return event-types
	 */
	public String[]  getEventTypes() {
		return (String[])eventtypes.toArray(new String [eventtypes.size()]);
	}

	/**
	 *  Set the event-types of this Register.
	 *  The system event types to be propagated to the tool.
	 * @param eventtypes the value to be set
	 */
	public void  setEventTypes(String[] eventtypes) {
		this.eventtypes.clear();
		for(int i=0; i<eventtypes.length; i++)
			this.eventtypes.add(eventtypes[i]);
	}

	/**
	 *  Get an event-types of this Register.
	 *  The system event types to be propagated to the tool.
	 *  @param idx The index.
	 *  @return event-types
	 */
	public String  getEventType(int idx) {
		return (String)this.eventtypes.get(idx);
	}

	/**
	 *  Set a event-type to this Register.
	 *  The system event types to be propagated to the tool.
	 *  @param idx The index.
	 *  @param eventtype a value to be added
	 */
	public void  setEventType(int idx, String eventtype) {
		this.eventtypes.set(idx, eventtype);
	}

	/**
	 *  Add a event-type to this Register.
	 *  The system event types to be propagated to the tool.
	 *  @param eventtype a value to be removed
	 */
	public void  addEventType(String eventtype)  {
		this.eventtypes.add(eventtype);
	}

	/**
	 *  Remove a event-type from this Register.
	 *  The system event types to be propagated to the tool.
	 *  @param eventtype a value to be removed
	 *  @return  True when the event-types have changed.
	 */
	public boolean  removeEventType(String eventtype)  {
		return this.eventtypes.remove(eventtype);
	}


	//-------- bean related methods --------

	/** The property descriptors, constructed on first access. */
	private java.beans.PropertyDescriptor[] pds = null;

	/**
	 *  Get the bean descriptor.
	 *  @return The bean descriptor.
	 */
	public java.beans.BeanDescriptor getBeanDescriptor() {
		return null;
	}

	/**
	 *  Get the property descriptors.
	 *  @return The property descriptors.
	 */
	public java.beans.PropertyDescriptor[] getPropertyDescriptors() {
		if(pds==null) {
			try {
				pds = new java.beans.PropertyDescriptor[]{
					 new java.beans.IndexedPropertyDescriptor("eventTypes", this.getClass(),
						"getEventTypes", "setEventTypes", "getEventType", "setEventType")
				};
				java.beans.PropertyDescriptor[] spds = super.getPropertyDescriptors();
				int	l1	= pds.length;
				int	l2	= spds.length;
				Object	res	= java.lang.reflect.Array.newInstance(java.beans.PropertyDescriptor.class, l1+l2);
				System.arraycopy(pds, 0, res, 0, l1);
				System.arraycopy(spds, 0, res, l1, l2);
				pds = (java.beans.PropertyDescriptor[])res;
			}
			catch(Exception e) {
				e.printStackTrace();
			}
		}
		return pds;
	}

	/**
	 *  Get the default property index.
	 *  @return The property index.
	 */
	public int getDefaultPropertyIndex() {
		return -1;
	}

	/**
	 *  Get the event set descriptors.
	 *  @return The event set descriptors.
	 */
	public java.beans.EventSetDescriptor[] getEventSetDescriptors() {
		return null;
	}

	/**
	 *  Get the default event index.
	 *  @return The default event index.
	 */
	public int getDefaultEventIndex() {
		return -1;
	}

	/**
	 *  Get the method descriptors.
	 *  @return The method descriptors.
	 */
	public java.beans.MethodDescriptor[] getMethodDescriptors() {
		return null;
	}

	/**
	 *  Get additional bean info.
	 *  @return Get additional bean info.
	 */
	public java.beans.BeanInfo[] getAdditionalBeanInfo() {
		return null;
	}

	/**
	 *  Get the icon.
	 *  @return The icon.
	 */
	public java.awt.Image getIcon(int iconKind) {
		return null;
	}

	/**
	 *  Load the image.
	 *  @return The image.
	 */
	public java.awt.Image loadImage(final String resourceName) {
		try {
			final Class c = getClass();
			java.awt.image.ImageProducer ip = (java.awt.image.ImageProducer)
				java.security.AccessController.doPrivileged(new java.security.PrivilegedAction() {
					public Object run(){
						java.net.URL url;
						if((url = c.getResource(resourceName))==null) {
							return null;
						}
						else {
							try {
								return url.getContent();
							}
							catch(java.io.IOException ioe) {
								return null;
							}
						}
					}
				});
			if(ip==null)
				return null;
			java.awt.Toolkit tk = java.awt.Toolkit.getDefaultToolkit();
			return tk.createImage(ip);
		}
		catch(Exception ex) {
			return null;
		}
	}

	//-------- additional methods --------

	/**
	 *  Get a string representation of this Register.
	 *  @return The string representation.
	 */
	public String toString() {
		return "Register("
		+ "tooltype="+getToolType()
           + ")";
	}

}
