/*
 * SystemEventBeanInfo.java
 *
 * Generated by Protege plugin Beanynizer.
 * Changes will be lost!
 */

package jadex.tools.ontology;

import jadex.runtime.*;


/**
 *  Java beaninfo class for concept SystemEvent of jadex.tools.introspector ontology.
 */
public class SystemEventBeanInfo extends java.beans.SimpleBeanInfo
{
	//-------- bean related methods --------

	/** The property descriptors, constructed on first access. */
	private java.beans.PropertyDescriptor[] pds = null;

	/**
	 *  Get the property descriptors.
	 *  @return The property descriptors.
	 */
	public java.beans.PropertyDescriptor[] getPropertyDescriptors() {
		if(pds==null) {
			try {
				pds = new java.beans.PropertyDescriptor[]{
					 new java.beans.PropertyDescriptor("type", SystemEvent.class, "getType", "setType")
					, new java.beans.PropertyDescriptor("cause", SystemEvent.class, "getCause", "setCause")
					, new java.beans.PropertyDescriptor("source", SystemEvent.class, "getSource", "setSource")
					, new java.beans.PropertyDescriptor("index", SystemEvent.class, "getIndex", "setIndex")
					, new java.beans.PropertyDescriptor("value", SystemEvent.class, "getValue", "setValue")
				};
			}
			catch(Exception e) {
				e.printStackTrace();
			}
		}
		return pds;
	}
}
