/*
 * RequestVision.java
 *
 * Generated by Protege plugin Beanynizer. 
 * Changes will be lost! 
 */
package jadex.examples.hunterprey;

import jadex.adapter.fipa.AgentAction;


/**
 *  Java class for concept RequestVision of hunterprey_beans ontology.
 */
public class RequestVision	extends AgentAction implements nuggets.INugget
{
	//-------- constants ----------

	//-------- attributes ----------

	/** The current vision of the creature. */
	protected  Vision  vision;

	/** The creature. */
	protected  Creature  creature;

	//-------- constructors --------

	/**
	 *  Default Constructor. <br>
	 *  Create a new <code>RequestVision</code>.
	 */
	public RequestVision()  { //
	}

	/**
	 *  Init Constructor. <br>
	 *  Create a new RequestVision.<br>
	 *  Initializes the object with required attributes.
	 * @param creature
	 */
	public RequestVision(Creature creature)  {
		this();
		setCreature(creature);
	}

	//-------- accessor methods --------

	/**
	 *  Get the vision of this RequestVision.
	 *  The current vision of the creature.
	 * @return vision
	 */
	public Vision  getVision() {
		return this.vision;
	}

	/**
	 *  Set the vision of this RequestVision.
	 *  The current vision of the creature.
	 * @param vision the value to be set
	 */
	public void  setVision(Vision vision) {
		this.vision = vision;
	}

	/**
	 *  Get the creature of this RequestVision.
	 *  The creature.
	 * @return creature
	 */
	public Creature  getCreature() {
		return this.creature;
	}

	/**
	 *  Set the creature of this RequestVision.
	 *  The creature.
	 * @param creature the value to be set
	 */
	public void  setCreature(Creature creature) {
		this.creature = creature;
	}

	//-------- object methods --------

	/**
	 *  Get a string representation of this RequestVision.
	 *  @return The string representation.
	 */
	public String toString() {
		return "RequestVision("
		+ "creature="+getCreature()
           + ")";
	}
	
	//--------- nuggets methods ---------
	
	/**
	 * Persist this RequestVision using the nuggets utility.
	 * @param c 
	 */
	public void _persist(nuggets.ICruncher c) {
		// declare references
		int idCreature = c.declare(creature);
		int idVision = c.declare(vision);
		// persist the nugget
		c.startConcept(this);
		if (idCreature>0) 
			c.put("Creature", idCreature);
		if (idVision>0) 
			c.put("Vision", idVision);
	}
	
	/**
	 * Restore this RequestVision 
	 * @param a the name of the attribute
	 * @param v the value of the attribute
	 */
	public void _set(String a, Object v) { //
		switch(hash(a)) {
		case 0: creature =  (Creature)v; return;
		case 1: vision =  (Vision)v; return;
		}                        
	}
	
private static final int hash(String name) {
   return ((2049123184*name.charAt(0))>>>15)%2;
}

}
