/*
 * RequestEat.java
 *
 * Generated by Protege plugin Beanynizer. 
 * Changes will be lost! 
 */
package jadex.examples.hunterprey;

import jadex.adapter.fipa.AgentAction;


/**
 *  Java class for concept RequestEat of hunterprey_beans ontology.
 */
public class RequestEat	extends AgentAction implements nuggets.INugget
{
	//-------- constants ----------

	//-------- attributes ----------

	/** The creature. */
	protected  Creature  creature;

	/** The object being eaten. */
	protected  WorldObject  object;

	//-------- constructors --------

	/**
	 *  Default Constructor. <br>
	 *  Create a new <code>RequestEat</code>.
	 */
	public RequestEat()  { //
	}

	/**
	 *  Init Constructor. <br>
	 *  Create a new RequestEat.<br>
	 *  Initializes the object with required attributes.
	 * @param creature
	 * @param object
	 */
	public RequestEat(Creature creature, WorldObject object)  {
		this();
		setCreature(creature);
		setObject(object);
	}

	//-------- accessor methods --------

	/**
	 *  Get the creature of this RequestEat.
	 *  The creature.
	 * @return creature
	 */
	public Creature  getCreature() {
		return this.creature;
	}

	/**
	 *  Set the creature of this RequestEat.
	 *  The creature.
	 * @param creature the value to be set
	 */
	public void  setCreature(Creature creature) {
		this.creature = creature;
	}

	/**
	 *  Get the object of this RequestEat.
	 *  The object being eaten.
	 * @return object
	 */
	public WorldObject  getObject() {
		return this.object;
	}

	/**
	 *  Set the object of this RequestEat.
	 *  The object being eaten.
	 * @param object the value to be set
	 */
	public void  setObject(WorldObject object) {
		this.object = object;
	}

	//-------- object methods --------

	/**
	 *  Get a string representation of this RequestEat.
	 *  @return The string representation.
	 */
	public String toString() {
		return "RequestEat("
		+ "creature="+getCreature()
		+ ", object="+getObject()
           + ")";
	}
	
	//--------- nuggets methods ---------
	
	/**
	 * Persist this RequestEat using the nuggets utility.
	 * @param c 
	 */
	public void _persist(nuggets.ICruncher c) {
		// declare references
		int idCreature = c.declare(creature);
		int idObject = c.declare(object);
		// persist the nugget
		c.startConcept(this);
		if (idCreature>0) 
			c.put("Creature", idCreature);
		if (idObject>0) 
			c.put("Object", idObject);
	}
	
	/**
	 * Restore this RequestEat 
	 * @param a the name of the attribute
	 * @param v the value of the attribute
	 */
	public void _set(String a, Object v) { //
		switch(hash(a)) {
		case 0: object =  (WorldObject)v; return;
		case 1: creature =  (Creature)v; return;
		}                        
	}
	
private static final int hash(String name) {
   return ((595730585*name.charAt(0))>>>15)%2;
}

}
