/*
 * WorldObjectData.java
 *
 * Generated by Protege plugin Beanynizer. 
 * Changes will be lost! 
 */
package jadex.examples.hunterprey;



/**
 *  Java class for concept WorldObject of hunterprey_beans ontology.
 */
public abstract class WorldObjectData implements nuggets.INugget
{
	//-------- constants ----------

	//-------- attributes ----------

	/** The location of the object. */
	protected  Location  location;

	//-------- constructors --------

	/**
	 *  Default Constructor. <br>
	 *  Create a new <code>WorldObject</code>.
	 */
	public WorldObjectData()  { //
	}

	//-------- accessor methods --------

	/**
	 *  Get the location of this WorldObject.
	 *  The location of the object.
	 * @return location
	 */
	public Location  getLocation() {
		return this.location;
	}

	/**
	 *  Set the location of this WorldObject.
	 *  The location of the object.
	 * @param location the value to be set
	 */
	public void  setLocation(Location location) {
		this.location = location;
	}

	//-------- object methods --------

	/**
	 *  Get a string representation of this WorldObject.
	 *  @return The string representation.
	 */
	public String toString() {
		return "WorldObject("
		+ "location="+getLocation()
           + ")";
	}
	
	//--------- nuggets methods ---------
	
	/**
	 * Persist this WorldObject using the nuggets utility.
	 * @param c 
	 */
	public void _persist(nuggets.ICruncher c) {
		// declare references
		int idLocation = c.declare(location);
		// persist the nugget
		c.startConcept(this);
		if (idLocation>0) 
			c.put("Location", idLocation);
	}
	
	/**
	 * Restore this WorldObject 
	 * @param a the name of the attribute
	 * @param v the value of the attribute
	 */
	public void _set(String a, Object v) { //
		location =  (Location)v; 
	}
}
