/*
 * TargetData.java
 *
 * Generated by Protege plugin Beanynizer. 
 * Changes will be lost! 
 */
package jadex.examples.marsworld;



/**
 *  Java class for concept Target of mars_beans ontology.
 */
public abstract class TargetData	extends LocationObject implements nuggets.INugget
{
	//-------- constants ----------

	//-------- attributes ----------

	//-------- constructors --------

	/**
	 *  Default Constructor. <br>
	 *  Create a new <code>Target</code>.
	 */
	public TargetData()  { //
	}

	//-------- accessor methods --------

	//-------- object methods --------

	/**
	 *  Get a string representation of this Target.
	 *  @return The string representation.
	 */
	public String toString() {
		return "Target("
		+ "id="+getId()
		+ ", location="+getLocation()
           + ")";
	}
	
	//--------- nuggets methods ---------
	
	/**
	 * Persist this Target using the nuggets utility.
	 * @param c 
	 */
	public void _persist(nuggets.ICruncher c) {
		// declare references
		int idLocation = c.declare(location);
		// persist the nugget
		c.startConcept(this);
		if (id!=null) 
			c.put("Id", id);
		if (idLocation>0) 
			c.put("Location", idLocation);
	}
	
	/**
	 * Restore this Target 
	 * @param a the name of the attribute
	 * @param v the value of the attribute
	 */
	public void _set(String a, Object v) { //
		switch(hash(a)) {
		case 0: id =  (String)v; return;
		case 1: location =  (Location)v; return;
		}                        
	}
	
private static final int hash(String name) {
   return ((873250401*name.charAt(0))>>>15)%2;
}

}
