/*
 * CardData.java
 *
 * Generated by Protege plugin Beanynizer. 
 * Changes will be lost! 
 */
package jadex.examples.blackjack;



/**
 *  Java class for concept Card of blackjack_beans ontology.
 */
public abstract class CardData implements java.beans.BeanInfo 
{
	//-------- constants ----------

	//-------- attributes ----------

	/** Attribute for slot col. */
	protected  String  col;

	/** Attribute for slot type. */
	protected  String  type;

	/** Attribute for slot val. */
	protected  int  val;

	//-------- constructors --------

	/**
	 *  Default Constructor. <br>
	 *  Create a new <code>Card</code>.
	 */
	public CardData()  {
	}

	//-------- accessor methods --------

	/**
	 *  Get the col of this Card.
	 * @return col
	 */
	public String  getColor() {
		return this.col;
	}

	/**
	 *  Set the col of this Card.
	 * @param col the value to be set
	 */
	public void  setColor(String col) {
		this.col = col;
	}

	/**
	 *  Get the type of this Card.
	 * @return type
	 */
	public String  getType() {
		return this.type;
	}

	/**
	 *  Set the type of this Card.
	 * @param type the value to be set
	 */
	public void  setType(String type) {
		this.type = type;
	}

	/**
	 *  Get the val of this Card.
	 * @return val
	 */
	public int  getValue() {
		return this.val;
	}

	/**
	 *  Set the val of this Card.
	 * @param val the value to be set
	 */
	public void  setValue(int val) {
		this.val = val;
	}

	//-------- bean related methods --------

	/** The property descriptors, constructed on first access. */
	private java.beans.PropertyDescriptor[] pds = null;

	/**
	 *  Get the bean descriptor.
	 *  @return The bean descriptor.
	 */
	public java.beans.BeanDescriptor getBeanDescriptor() {
		return null;
	}

	/**
	 *  Get the property descriptors.
	 *  @return The property descriptors.
	 */
	public java.beans.PropertyDescriptor[] getPropertyDescriptors() {
		if(pds==null) {
			try {
				pds = new java.beans.PropertyDescriptor[]{
					 new java.beans.PropertyDescriptor("col", this.getClass(), "getColor", "setColor")
					, new java.beans.PropertyDescriptor("type", this.getClass(), "getType", "setType")
					, new java.beans.PropertyDescriptor("val", this.getClass(), "getValue", "setValue")
				};
			}
			catch(Exception e) {
				e.printStackTrace();
			}
		}
		return pds;
	}

	/**
	 *  Get the default property index.
	 *  @return The property index.
	 */
	public int getDefaultPropertyIndex() {
		return -1;
	}

	/**
	 *  Get the event set descriptors.
	 *  @return The event set descriptors.
	 */
	public java.beans.EventSetDescriptor[] getEventSetDescriptors() {
		return null;
	}

	/**
	 *  Get the default event index.
	 *  @return The default event index.
	 */
	public int getDefaultEventIndex() {
		return -1;
	}

	/**
	 *  Get the method descriptors.
	 *  @return The method descriptors.
	 */
	public java.beans.MethodDescriptor[] getMethodDescriptors() {
		return null;
	}

	/**
	 *  Get additional bean info.
	 *  @return Get additional bean info.
	 */
	public java.beans.BeanInfo[] getAdditionalBeanInfo() {
		return null;
	}

	/**
	 *  Get the icon.
	 *  @return The icon.
	 */
	public java.awt.Image getIcon(int iconKind) {
		return null;
	}

	/**
	 *  Load the image.
	 *  @return The image.
	 */
	public java.awt.Image loadImage(final String resourceName) {
		try {
			final Class c = getClass();
			java.awt.image.ImageProducer ip = (java.awt.image.ImageProducer)
				java.security.AccessController.doPrivileged(new java.security.PrivilegedAction() {
					public Object run(){
						java.net.URL url;
						if((url = c.getResource(resourceName))==null) {
							return null;
						}
						else {
							try {
								return url.getContent();
							}
							catch(java.io.IOException ioe) {
								return null;
							}
						}
					}
				});
			if(ip==null)
				return null;
			java.awt.Toolkit tk = java.awt.Toolkit.getDefaultToolkit();
			return tk.createImage(ip);
		}
		catch(Exception ex) {
			return null;
		}
	}

	//-------- additional methods --------

	/**
	 *  Get a string representation of this Card.
	 *  @return The string representation.
	 */
	public String toString() {
		return "Card("
           + ")";
	}

}
