/*
 * $class.javaName.java
 *
 * Generated by Protege plugin Beanynizer. 
 * This class implements the functionality of Card.
 * Feel free to change.
 *
 */
package jadex.examples.blackjack;


/**
 * Editable Java class for concept <code>Card</code> of blackjack_beans ontology.
 */
public class Card extends CardData
{
	//-------- constructors --------

	/**
	 * Default Constructor. <br>
	 * Create a new <code>Card</code>.
	 */
	public Card()
	{
		// Empty constructor required for JavaBeans (do not remove).
	}

	/**
	 * Default Constructor. <br>
	 * Create a new <code>Card</code>.
	 */
	public Card(String type, String color, int value)
	{
		setType(type);
		setColor(color);
		setValue(value);
	}

	/**
	 * Clone Constructor. <br>
	 * Create a new <code>Card</code>.<br>
	 * Copy all attributes from <code>proto</code> to this instance.
	 * @param proto The prototype instance.
	 */
	public Card(Card proto)
	{
		setColor(proto.getColor());
		setType(proto.getType());
		setValue(proto.getValue());
	}

	//-------- custom code --------


	//-------- Object methods -----

	/**
	 * Get a string representation of this <code>Card</code>.
	 * @return The string representation.
	 */
	public String toString()
	{
		return getType()+" "+getColor();
	}

	/**
	 * Get a clone of this <code>Card</code>.
	 * @return a shalow copy of this instance.
	 */
	public Object clone()
	{
		return new Card(this);
	}

	/**
	 * Test the equality of this <code>Card</code>
	 * and an object <code>obj</code>.
	 * @param obj the object this test will be performed with
	 * @return false if <code>obj</code> is not of <code>Card</code> class,
	 *         true if all attributes are equal.
	 */
	public boolean equals(Object obj)
	{
		if(obj instanceof Card)
		{
			Card cmp = (Card)obj;
			if(getColor()!=cmp.getColor() &&
					(getColor()==null || !getColor().equals(cmp.getColor()))
			)
				return false;
			if(getType()!=cmp.getType() &&
					(getType()==null || !getType().equals(cmp.getType()))
			)
				return false;
			if(getValue()!=cmp.getValue()) return false;
			return true;
		}
		return false;
	}
}

