/*
 * RequestDraw.java
 *
 * Generated by Protege plugin Beanynizer. 
 * Changes will be lost! 
 */
package jadex.examples.blackjack;

import jadex.adapter.fipa.AgentAction;
import java.util.ArrayList;
import java.util.List;


/**
 *  Java class for concept RequestDraw of blackjack_beans ontology.
 */
public class RequestDraw	extends AgentAction implements java.beans.BeanInfo 
{
	//-------- constants ----------

	//-------- attributes ----------

	/** Attribute for slot cards. */
	protected  List  cards;

	//-------- constructors --------

	/**
	 *  Default Constructor. <br>
	 *  Create a new <code>RequestDraw</code>.
	 */
	public RequestDraw()  {
		this.cards  = new ArrayList();
	}

	//-------- accessor methods --------

	/**
	 *  Get the cards of this RequestDraw.
	 * @return cards
	 */
	public Card[]  getCards() {
		return (Card[])cards.toArray(new Card [cards.size()]);
	}

	/**
	 *  Set the cards of this RequestDraw.
	 * @param cards the value to be set
	 */
	public void  setCards(Card[] cards) {
		this.cards.clear();
		for(int i=0; i<cards.length; i++)
			this.cards.add(cards[i]);
	}

	/**
	 *  Get an cards of this RequestDraw.
	 *  @param idx The index.
	 *  @return cards
	 */
	public Card  getCard(int idx) {
		return (Card)this.cards.get(idx);
	}

	/**
	 *  Set a card to this RequestDraw.
	 *  @param idx The index.
	 *  @param card a value to be added
	 */
	public void  setCard(int idx, Card card) {
		this.cards.set(idx, card);
	}

	/**
	 *  Add a card to this RequestDraw.
	 *  @param card a value to be removed
	 */
	public void  addCard(Card card)  {
		this.cards.add(card);
	}

	/**
	 *  Remove a card from this RequestDraw.
	 *  @param card a value to be removed
	 *  @return  True when the cards have changed.
	 */
	public boolean  removeCard(Card card)  {
		return this.cards.remove(card);
	}


	//-------- bean related methods --------

	/** The property descriptors, constructed on first access. */
	private java.beans.PropertyDescriptor[] pds = null;

	/**
	 *  Get the bean descriptor.
	 *  @return The bean descriptor.
	 */
	public java.beans.BeanDescriptor getBeanDescriptor() {
		return null;
	}

	/**
	 *  Get the property descriptors.
	 *  @return The property descriptors.
	 */
	public java.beans.PropertyDescriptor[] getPropertyDescriptors() {
		if(pds==null) {
			try {
				pds = new java.beans.PropertyDescriptor[]{
					 new java.beans.IndexedPropertyDescriptor("cards", this.getClass(),
						"getCards", "setCards", "getCard", "setCard")
				};
				java.beans.PropertyDescriptor[] spds = super.getPropertyDescriptors();
				int	l1	= pds.length;
				int	l2	= spds.length;
				Object	res	= java.lang.reflect.Array.newInstance(java.beans.PropertyDescriptor.class, l1+l2);
				System.arraycopy(pds, 0, res, 0, l1);
				System.arraycopy(spds, 0, res, l1, l2);
				pds = (java.beans.PropertyDescriptor[])res;
			}
			catch(Exception e) {
				e.printStackTrace();
			}
		}
		return pds;
	}

	/**
	 *  Get the default property index.
	 *  @return The property index.
	 */
	public int getDefaultPropertyIndex() {
		return -1;
	}

	/**
	 *  Get the event set descriptors.
	 *  @return The event set descriptors.
	 */
	public java.beans.EventSetDescriptor[] getEventSetDescriptors() {
		return null;
	}

	/**
	 *  Get the default event index.
	 *  @return The default event index.
	 */
	public int getDefaultEventIndex() {
		return -1;
	}

	/**
	 *  Get the method descriptors.
	 *  @return The method descriptors.
	 */
	public java.beans.MethodDescriptor[] getMethodDescriptors() {
		return null;
	}

	/**
	 *  Get additional bean info.
	 *  @return Get additional bean info.
	 */
	public java.beans.BeanInfo[] getAdditionalBeanInfo() {
		return null;
	}

	/**
	 *  Get the icon.
	 *  @return The icon.
	 */
	public java.awt.Image getIcon(int iconKind) {
		return null;
	}

	/**
	 *  Load the image.
	 *  @return The image.
	 */
	public java.awt.Image loadImage(final String resourceName) {
		try {
			final Class c = getClass();
			java.awt.image.ImageProducer ip = (java.awt.image.ImageProducer)
				java.security.AccessController.doPrivileged(new java.security.PrivilegedAction() {
					public Object run(){
						java.net.URL url;
						if((url = c.getResource(resourceName))==null) {
							return null;
						}
						else {
							try {
								return url.getContent();
							}
							catch(java.io.IOException ioe) {
								return null;
							}
						}
					}
				});
			if(ip==null)
				return null;
			java.awt.Toolkit tk = java.awt.Toolkit.getDefaultToolkit();
			return tk.createImage(ip);
		}
		catch(Exception ex) {
			return null;
		}
	}

	//-------- additional methods --------

	/**
	 *  Get a string representation of this RequestDraw.
	 *  @return The string representation.
	 */
	public String toString() {
		return "RequestDraw("
           + ")";
	}

}
