/*
 * LocationObjectData.java
 *
 * Generated by Protege plugin Beanynizer. 
 * Changes will be lost! 
 */
package jadex.examples.cleanerworld.multi;



/**
 *  Java class for concept LocationObject of cleaner_beans ontology.
 */
public abstract class LocationObjectData implements nuggets.INugget, java.io.Serializable
{
	//-------- constants ----------

	//-------- attributes ----------

	/** Attribute for slot id. */
	protected  String  id;

	/** The location of the object. */
	protected  Location  location;

	//-------- constructors --------

	/**
	 *  Default Constructor. <br>
	 *  Create a new <code>LocationObject</code>.
	 */
	public LocationObjectData()  { //
	}

	//-------- accessor methods --------

	/**
	 *  Get the id of this LocationObject.
	 * @return id
	 */
	public String  getId() {
		return this.id;
	}

	/**
	 *  Set the id of this LocationObject.
	 * @param id the value to be set
	 */
	public void  setId(String id) {
		this.id = id;
	}

	/**
	 *  Get the location of this LocationObject.
	 *  The location of the object.
	 * @return location
	 */
	public Location  getLocation() {
		return this.location;
	}

	/**
	 *  Set the location of this LocationObject.
	 *  The location of the object.
	 * @param location the value to be set
	 */
	public void  setLocation(Location location) {
		this.location = location;
	}

	//-------- object methods --------

	/**
	 *  Get a string representation of this LocationObject.
	 *  @return The string representation.
	 */
	public String toString() {
		return "LocationObject("
		+ "id="+getId()
		+ ", location="+getLocation()
           + ")";
	}
	
	//--------- nuggets methods ---------
	
	/**
	 * Persist this LocationObject using the nuggets utility.
	 * @param c 
	 */
	public void _persist(nuggets.ICruncher c) {
		// declare references
		int idLocation = c.declare(location);
		// persist the nugget
		c.startConcept(this);
		if (id!=null) 
			c.put("Id", id);
		if (idLocation>0) 
			c.put("Location", idLocation);
	}
	
	/**
	 * Restore this LocationObject 
	 * @param a the name of the attribute
	 * @param v the value of the attribute
	 */
	public void _set(String a, Object v) { //
		switch(hash(a)) {
		case 0: location =  (Location)v; return;
		case 1: id =  (String)v; return;
		}                        
	}
	
private static final int hash(String name) {
   return ((638877823*name.charAt(0))>>>15)%2;
}

}
