/*
 * RequestDropWaste.java
 *
 * Generated by Protege plugin Beanynizer. 
 * Changes will be lost! 
 */
package jadex.examples.cleanerworld.multi;

import jadex.adapter.fipa.AgentAction;


/**
 *  Java class for concept RequestDropWaste of cleaner_beans ontology.
 */
public class RequestDropWaste	extends AgentAction implements nuggets.INugget
{
	//-------- constants ----------

	//-------- attributes ----------

	/** Attribute for slot waste. */
	protected  Waste  waste;

	/** Attribute for slot wastebinname. */
	protected  String  wastebinname;

	//-------- constructors --------

	/**
	 *  Default Constructor. <br>
	 *  Create a new <code>RequestDropWaste</code>.
	 */
	public RequestDropWaste()  { //
	}

	//-------- accessor methods --------

	/**
	 *  Get the waste of this RequestDropWaste.
	 * @return waste
	 */
	public Waste  getWaste() {
		return this.waste;
	}

	/**
	 *  Set the waste of this RequestDropWaste.
	 * @param waste the value to be set
	 */
	public void  setWaste(Waste waste) {
		this.waste = waste;
	}

	/**
	 *  Get the wastebinname of this RequestDropWaste.
	 * @return wastebinname
	 */
	public String  getWastebinname() {
		return this.wastebinname;
	}

	/**
	 *  Set the wastebinname of this RequestDropWaste.
	 * @param wastebinname the value to be set
	 */
	public void  setWastebinname(String wastebinname) {
		this.wastebinname = wastebinname;
	}

	//-------- object methods --------

	/**
	 *  Get a string representation of this RequestDropWaste.
	 *  @return The string representation.
	 */
	public String toString() {
		return "RequestDropWaste("
           + ")";
	}
	
	//--------- nuggets methods ---------
	
	/**
	 * Persist this RequestDropWaste using the nuggets utility.
	 * @param c 
	 */
	public void _persist(nuggets.ICruncher c) {
		// declare references
		int idWaste = c.declare(waste);
		// persist the nugget
		c.startConcept(this);
		if (idWaste>0) 
			c.put("Waste", idWaste);
		if (wastebinname!=null) 
			c.put("Wastebinname", wastebinname);
	}
	
	/**
	 * Restore this RequestDropWaste 
	 * @param a the name of the attribute
	 * @param v the value of the attribute
	 */
	public void _set(String a, Object v) { //
		switch(hash(a)) {
		case 0: waste =  (Waste)v; return;
		case 1: wastebinname =  (String)v; return;
		}                        
	}
	
private static final int hash(String name) {
  int h=0;
  int c=name.length();
   if (c<=5) return 0;
   h += 1023232694*name.charAt(5);
   return (h>>>15)%2;
}

}
