/*
 * RequestPickUpWaste.java
 *
 * Generated by Protege plugin Beanynizer. 
 * Changes will be lost! 
 */
package jadex.examples.cleanerworld.multi;

import jadex.adapter.fipa.AgentAction;


/**
 *  Java class for concept RequestPickUpWaste of cleaner_beans ontology.
 */
public class RequestPickUpWaste	extends AgentAction implements nuggets.INugget
{
	//-------- constants ----------

	//-------- attributes ----------

	/** Attribute for slot waste. */
	protected  Waste  waste;

	//-------- constructors --------

	/**
	 *  Default Constructor. <br>
	 *  Create a new <code>RequestPickUpWaste</code>.
	 */
	public RequestPickUpWaste()  { //
	}

	//-------- accessor methods --------

	/**
	 *  Get the waste of this RequestPickUpWaste.
	 * @return waste
	 */
	public Waste  getWaste() {
		return this.waste;
	}

	/**
	 *  Set the waste of this RequestPickUpWaste.
	 * @param waste the value to be set
	 */
	public void  setWaste(Waste waste) {
		this.waste = waste;
	}

	//-------- object methods --------

	/**
	 *  Get a string representation of this RequestPickUpWaste.
	 *  @return The string representation.
	 */
	public String toString() {
		return "RequestPickUpWaste("
           + ")";
	}
	
	//--------- nuggets methods ---------
	
	/**
	 * Persist this RequestPickUpWaste using the nuggets utility.
	 * @param c 
	 */
	public void _persist(nuggets.ICruncher c) {
		// declare references
		int idWaste = c.declare(waste);
		// persist the nugget
		c.startConcept(this);
		if (idWaste>0) 
			c.put("Waste", idWaste);
	}
	
	/**
	 * Restore this RequestPickUpWaste 
	 * @param a the name of the attribute
	 * @param v the value of the attribute
	 */
	public void _set(String a, Object v) { //
		waste =  (Waste)v; 
	}
}
