/*
 * PositionBeanInfo.java
 *
 * Generated by Protege plugin Beanynizer.
 * Changes will be lost!
 */

package jadex.examples.puzzle.humanplayer;

import jadex.examples.puzzle.*;


/**
 *  Java beaninfo class for concept Position of puzzle ontology.
 */
public class PositionBeanInfo extends java.beans.SimpleBeanInfo
{
	//-------- bean related methods --------

	/** The property descriptors, constructed on first access. */
	private java.beans.PropertyDescriptor[] pds = null;

	/**
	 *  Get the property descriptors.
	 *  @return The property descriptors.
	 */
	public java.beans.PropertyDescriptor[] getPropertyDescriptors() {
		if(pds==null) {
			try {
				pds = new java.beans.PropertyDescriptor[]{
					 new java.beans.PropertyDescriptor("x", Position.class, "getX", "setX")
					, new java.beans.PropertyDescriptor("y", Position.class, "getY", "setY")
				};
			}
			catch(Exception e) {
				e.printStackTrace();
			}
		}
		return pds;
	}
}
